exporter_port: 8080 # Port on which prometheu can call this exporter to get metrics
log_level: info
json_data_url: http://jvb:8080/colibri/stats # Url to get json data used for fetching metric values
metric_name_prefix: jitsi # All metric names will be prefixed with this value
metrics:
- name: packet_rate_download
  path: $.packet_rate_download
- name: total_tcp_connections
  path: $.total_tcp_connections
- name: total_packets_sent_octo
  path: $.total_packets_sent_octo
- name: total_loss_degraded_participant_seconds
  path: $.total_loss_degraded_participant_seconds
- name: bit_rate_download
  path: $.bit_rate_download
- name: videostreams
  path: $.videostreams
- name: jitter_aggregate
  path: $.jitter_aggregate
- name: total_channels
  path: $.total_channels
- name: total_memory
  path: $.total_memory
- name: total_packets_received
  path: $.total_packets_received
- name: rtt_aggregate
  path: $.rtt_aggregate
- name: packet_rate_upload
  path: $.packet_rate_upload
- name: conferences
  path: $.conferences
- name: participants
  path: $.participants
- name: total_loss_limited_participant_seconds
  path: $.total_loss_limited_participant_seconds
- name: largest_conference
  path: $.largest_conference
- name: total_packets_sent
  path: $.total_packets_sent
- name: total_data_channel_messages_sent
  path: $.total_data_channel_messages_sent
- name: total_bytes_received_octo
  path: $.total_bytes_received_octo
- name: total_no_transport_channels
  path: $.total_no_transport_channels
- name: total_no_payload_channels
  path: $.total_no_payload_channels
- name: used_memory
  path: $.used_memory
- name: total_conferences_created
  path: $.total_conferences_created
- name: threads
  path: $.threads
- name: total_colibri_web_socket_messages_received
  path: $.total_colibri_web_socket_messages_received
- name: videochannels
  path: $.videochannels
- name: total_udp_connections
  path: $.total_udp_connections
- name: loss_rate_upload
  path: $.loss_rate_upload
- name: total_packets_received_octo
  path: $.total_packets_received_octo
- name: graceful_shutdown
  path: $.graceful_shutdown
- name: total_colibri_web_socket_messages_sent
  path: $.total_colibri_web_socket_messages_sent
- name: total_bytes_sent_octo
  path: $.total_bytes_sent_octo
- name: total_data_channel_messages_received
  path: $.total_data_channel_messages_received
- name: loss_rate_download
  path: $.loss_rate_download
- name: total_conference_seconds
  path: $.total_conference_seconds
- name: total_bytes_received
  path: $.total_bytes_received
- name: rtp_loss
  path: $.rtp_loss
- name: total_loss_controlled_participant_seconds
  path: $.total_loss_controlled_participant_seconds
- name: total_partially_failed_conferences
  path: $.total_partially_failed_conferences
- name: bit_rate_upload
  path: $.bit_rate_upload
- name: total_conferences_completed
  path: $.total_conferences_completed
- name: total_bytes_sent
  path: $.total_bytes_sent
- name: total_failed_conferences
  path: $.total_failed_conferences
- name: cpu_usage
  path: $.cpu_usage
- name: audiochannels
  path: $.audiochannels